import type { Lesson } from '../../domain/content';

/** Aulas do nível Básico (Análise de requisitos §15). */
export const basicLessons: Lesson[] = [
  {
    id: 'simple-present',
    level: 'basic',
    order: 6,
    title: 'Presente simples: rotina e hábitos',
    topic: 'Simple Present',
    summary: 'Fale da sua rotina e use o -s com he, she e it.',
    estimatedMinutes: 10,
    skillTags: ['simple_present'],
    objectives: [
      'Usar o presente simples para rotinas e fatos',
      'Adicionar -s (ou -es) ao verbo com he, she e it',
      'Posicionar always, usually, sometimes e never',
    ],
    explanation: [
      {
        pt: 'Usamos o presente simples para rotinas, hábitos e fatos: I work every day. The sun rises in the east.',
        en: 'We use the simple present for routines, habits and facts: I work every day. The sun rises in the east.',
      },
      {
        pt: 'Com he, she e it, normalmente adicionamos -s ao verbo: I work → she works; I live → he lives.',
        en: 'With he, she and it, we usually add -s to the verb: I work → she works; I live → he lives.',
      },
      {
        pt: 'Alguns verbos mudam um pouco: go → goes, do → does, watch → watches, study → studies, have → has.',
        en: 'Some verbs change a little: go → goes, do → does, watch → watches, study → studies, have → has.',
      },
      {
        pt: 'Palavras de frequência (always, usually, often, sometimes, never) costumam vir antes do verbo: I usually drink coffee.',
        en: 'Frequency words (always, usually, often, sometimes, never) usually come before the verb: I usually drink coffee.',
      },
    ],
    alternativeExplanations: [
      {
        pt: 'Pense no -s como uma "etiqueta" da terceira pessoa: quando o sujeito é UMA pessoa ou coisa que não é você nem eu (he, she, it, my mom, the dog), o verbo ganha -s.',
        en: 'Think of -s as a "label" for the third person: when the subject is ONE person or thing that is not "I" or "you", the verb gets -s.',
      },
      {
        pt: 'Um teste rápido: troque o sujeito por "he" ou "she". Se der certo, o verbo leva -s. "My boss (= he) works from home."',
        en: 'A quick test: replace the subject with "he" or "she". If it works, the verb takes -s. "My boss (= he) works from home."',
      },
    ],
    table: {
      caption: 'Presente simples',
      headers: ['Sujeito', 'work', 'go', 'have', 'study'],
      rows: [
        ['I / You / We / They', 'work', 'go', 'have', 'study'],
        ['He / She / It', 'works', 'goes', 'has', 'studies'],
      ],
    },
    examples: [
      { en: 'She goes to school every day.', pt: 'Ela vai à escola todos os dias.', highlight: 'goes' },
      { en: 'My father works from home.', pt: 'Meu pai trabalha de casa.', highlight: 'works' },
      { en: 'I usually wake up at 7.', pt: 'Eu geralmente acordo às 7.', highlight: 'usually' },
      { en: 'He watches TV at night.', pt: 'Ele assiste TV à noite.', highlight: 'watches' },
    ],
    extraExamples: [
      { en: 'Our class starts at 8 a.m.', pt: 'Nossa aula começa às 8h.', highlight: 'starts' },
      { en: 'She never drinks coffee.', pt: 'Ela nunca bebe café.', highlight: 'never drinks' },
      { en: 'My cat sleeps all day.', pt: 'Meu gato dorme o dia todo.', highlight: 'sleeps' },
    ],
    vocabularyIds: ['every-day', 'usually', 'always', 'never', 'wake-up', 'breakfast', 'work'],
    exercises: [
      {
        id: 'present-1',
        lessonId: 'simple-present',
        type: 'select_word',
        instruction: 'Selecione a forma correta do verbo.',
        prompt: 'She ___ to school every day.',
        options: ['goes', 'go', 'going', 'gos'],
        acceptedAnswers: ['goes'],
        explanation: {
          pt: 'Com he, she e it, normalmente adicionamos -s ao verbo no presente simples. "Go" vira "goes".',
          en: 'With he, she and it, we usually add -s to the verb in the simple present. "Go" becomes "goes".',
        },
        skillTag: 'simple_present',
      },
      {
        id: 'present-2',
        lessonId: 'simple-present',
        type: 'select_word',
        instruction: 'Selecione a forma correta do verbo.',
        prompt: 'My brother ___ in São Paulo.',
        options: ['lives', 'live', 'living', 'is live'],
        acceptedAnswers: ['lives'],
        explanation: {
          pt: '"My brother" equivale a "he", então o verbo recebe -s: lives.',
          en: '"My brother" is the same as "he", so the verb takes -s: lives.',
        },
        skillTag: 'simple_present',
      },
      {
        id: 'present-3',
        lessonId: 'simple-present',
        type: 'fill_blank',
        instruction: 'Complete com o verbo "have" no presente simples.',
        prompt: 'He ___ a new job.',
        acceptedAnswers: ['has'],
        explanation: {
          pt: '"Have" é irregular com he, she e it: vira "has". He has a new job.',
          en: '"Have" is irregular with he, she and it: it becomes "has".',
        },
        skillTag: 'simple_present',
      },
      {
        id: 'present-4',
        lessonId: 'simple-present',
        type: 'multiple_choice',
        instruction: 'Escolha a frase correta.',
        prompt: 'Qual frase está correta?',
        options: [
          'I usually drink coffee in the morning.',
          'I drink usually coffee in the morning.',
          'Usually I drinks coffee in the morning.',
          'I usually drinks coffee in the morning.',
        ],
        acceptedAnswers: ['I usually drink coffee in the morning.'],
        explanation: {
          pt: 'Palavras de frequência (always, usually, never…) vêm antes do verbo principal. E com "I" o verbo não recebe -s.',
          en: 'Frequency words come before the main verb. With "I", the verb does not take -s.',
        },
        skillTag: 'simple_present',
      },
      {
        id: 'present-5',
        lessonId: 'simple-present',
        type: 'write',
        instruction: 'Escreva uma frase sobre a rotina de alguém usando he ou she.',
        prompt: 'Write about someone\'s routine using "he" or "she".',
        acceptedAnswers: [],
        requirements: [{ pattern: '\\b(he|she)\\b', message: 'Use "he" ou "she" na sua frase.' }],
        minWords: 4,
        explanation: {
          pt: 'Com he, she e it, o verbo no presente simples recebe -s: She works, He goes, She studies.',
          en: 'With he, she and it, the simple present verb takes -s: She works, He goes, She studies.',
        },
        skillTag: 'simple_present',
      },
      {
        id: 'present-6',
        lessonId: 'simple-present',
        type: 'translate',
        instruction: 'Traduza para o inglês.',
        prompt: 'Ela estuda inglês todos os dias.',
        acceptedAnswers: ['She studies English every day.'],
        explanation: {
          pt: '"Study" com she vira "studies" (o y vira -ies). "Todos os dias" é "every day" (duas palavras).',
          en: '"Study" with she becomes "studies". "Every day" is two words here.',
          tip: {
            pt: '"Everyday" (junto) é um adjetivo: everyday objects = objetos do dia a dia.',
            en: '"Everyday" (one word) is an adjective: everyday objects.',
          },
        },
        skillTag: 'simple_present',
      },
    ],
    practice: {
      opener: {
        en: "Let's talk about routines! I'm {assistant}. What time do you usually wake up?",
        pt: 'Vamos falar de rotina! Eu sou {assistant}. Que horas você geralmente acorda?',
      },
      question: 'What time do you usually wake up?',
    },
    takeaways: [
      'Presente simples = rotinas, hábitos e fatos.',
      'He/she/it + verbo com -s (goes, has, studies).',
      'Frequência antes do verbo: I usually…',
    ],
  },
  {
    id: 'questions-negatives',
    level: 'basic',
    order: 7,
    title: 'Perguntas e negativas com do/does',
    topic: 'Questions & negatives',
    summary: 'Pergunte e negue no presente simples sem tropeçar no -s.',
    estimatedMinutes: 9,
    skillTags: ['questions_negatives'],
    objectives: [
      'Fazer perguntas com do e does',
      'Negar com don\'t e doesn\'t',
      'Dar respostas curtas (Yes, I do / No, she doesn\'t)',
    ],
    explanation: [
      {
        pt: 'Para perguntar no presente simples, usamos "do" (I, you, we, they) ou "does" (he, she, it) antes do sujeito: Do you like pizza? Does she work here?',
        en: 'To ask questions in the simple present, use "do" (I, you, we, they) or "does" (he, she, it) before the subject.',
      },
      {
        pt: 'Com "does", o verbo principal volta para a forma básica: Does he play? (e não "Does he plays?"). O -s já está no "does".',
        en: 'With "does", the main verb goes back to its base form: Does he play? (not "Does he plays?").',
      },
      {
        pt: 'Na negativa, use "don\'t" (do not) e "doesn\'t" (does not): I don\'t eat meat. She doesn\'t drive.',
        en: "For negatives, use \"don't\" and \"doesn't\": I don't eat meat. She doesn't drive.",
      },
      {
        pt: 'Atenção: o verbo to be não usa do/does. "Are you tired?" e "She isn\'t here".',
        en: "Remember: the verb to be does not use do/does. \"Are you tired?\" and \"She isn't here\".",
      },
    ],
    alternativeExplanations: [
      {
        pt: 'Imagine que o "does" "rouba" o -s do verbo: She works → Does she work? → She doesn\'t work. O -s só aparece uma vez.',
        en: "Imagine \"does\" \"steals\" the -s from the verb: She works → Does she work? → She doesn't work.",
      },
      {
        pt: 'Pergunta = Do/Does + sujeito + verbo básico. Negativa = sujeito + don\'t/doesn\'t + verbo básico. É sempre a mesma fórmula.',
        en: "Question = Do/Does + subject + base verb. Negative = subject + don't/doesn't + base verb.",
      },
    ],
    table: {
      caption: 'Afirmativa, negativa e pergunta',
      headers: ['Afirmativa', 'Negativa', 'Pergunta'],
      rows: [
        ['I work', "I don't work", 'Do I work?'],
        ['You like tea', "You don't like tea", 'Do you like tea?'],
        ['She works', "She doesn't work", 'Does she work?'],
        ['It rains', "It doesn't rain", 'Does it rain?'],
      ],
    },
    examples: [
      { en: 'Do you speak Spanish?', pt: 'Você fala espanhol?', highlight: 'Do you' },
      { en: "He doesn't like coffee.", pt: 'Ele não gosta de café.', highlight: "doesn't like" },
      { en: 'Does your sister live here? — Yes, she does.', pt: 'Sua irmã mora aqui? — Sim, mora.', highlight: 'Does' },
    ],
    extraExamples: [
      { en: "We don't work on Sundays.", pt: 'Nós não trabalhamos aos domingos.', highlight: "don't work" },
      { en: 'Does the store open at 9?', pt: 'A loja abre às 9?', highlight: 'Does the store open' },
      { en: 'Do they have kids? — No, they don\'t.', pt: 'Eles têm filhos? — Não, não têm.', highlight: 'Do they have' },
    ],
    vocabularyIds: ['speak', 'like', 'drive'],
    exercises: [
      {
        id: 'questions-1',
        lessonId: 'questions-negatives',
        type: 'select_word',
        instruction: 'Selecione o auxiliar correto.',
        prompt: '___ she speak Spanish?',
        options: ['Does', 'Do', 'Is', 'Are'],
        acceptedAnswers: ['Does'],
        explanation: {
          pt: 'Com he, she e it usamos "does" para perguntar: Does she speak Spanish?',
          en: 'With he, she and it we use "does" in questions.',
        },
        skillTag: 'questions_negatives',
      },
      {
        id: 'questions-2',
        lessonId: 'questions-negatives',
        type: 'select_word',
        instruction: 'Selecione a negativa correta.',
        prompt: 'I ___ like horror movies.',
        options: ["don't", "doesn't", 'not', 'am not'],
        acceptedAnswers: ["don't"],
        explanation: {
          pt: 'Com "I" usamos "don\'t" na negativa: I don\'t like horror movies.',
          en: "With \"I\" we use \"don't\": I don't like horror movies.",
        },
        skillTag: 'questions_negatives',
      },
      {
        id: 'questions-3',
        lessonId: 'questions-negatives',
        type: 'multiple_choice',
        instruction: 'Escolha a pergunta correta.',
        prompt: 'Qual pergunta está correta?',
        options: [
          'Does he play the guitar?',
          'Does he plays the guitar?',
          'Do he play the guitar?',
          'He does play the guitar?',
        ],
        acceptedAnswers: ['Does he play the guitar?'],
        explanation: {
          pt: 'Com "does", o verbo principal fica na forma básica: Does he play…? O -s já está no "does".',
          en: 'With "does", the main verb stays in the base form: Does he play…?',
        },
        skillTag: 'questions_negatives',
      },
      {
        id: 'questions-4',
        lessonId: 'questions-negatives',
        type: 'fill_blank',
        instruction: 'Complete com a forma negativa (does not).',
        prompt: 'My father ___ drink coffee.',
        acceptedAnswers: ["doesn't", 'does not'],
        explanation: {
          pt: '"My father" equivale a "he", então a negativa é "doesn\'t": My father doesn\'t drink coffee.',
          en: "\"My father\" is \"he\", so the negative is \"doesn't\".",
        },
        skillTag: 'questions_negatives',
      },
      {
        id: 'questions-5',
        lessonId: 'questions-negatives',
        type: 'translate',
        instruction: 'Traduza para o inglês.',
        prompt: 'Você mora aqui?',
        acceptedAnswers: ['Do you live here?'],
        explanation: {
          pt: 'Perguntas no presente simples começam com "Do" (para you): Do you live here?',
          en: 'Simple present questions with "you" start with "Do".',
        },
        skillTag: 'questions_negatives',
      },
      {
        id: 'questions-6',
        lessonId: 'questions-negatives',
        type: 'multiple_choice',
        instruction: 'Escolha a resposta curta positiva.',
        prompt: '"Do you like tea?"',
        options: ['Yes, I do.', 'Yes, I like.', 'Yes, I am.', 'Yes, I does.'],
        acceptedAnswers: ['Yes, I do.'],
        explanation: {
          pt: 'A resposta curta repete o auxiliar da pergunta: Do you…? → Yes, I do.',
          en: 'Short answers repeat the auxiliary: Do you…? → Yes, I do.',
        },
        skillTag: 'questions_negatives',
      },
    ],
    practice: {
      opener: {
        en: "Let's ask and answer questions! I'm {assistant}. Do you like coffee?",
        pt: 'Vamos perguntar e responder! Eu sou {assistant}. Você gosta de café?',
      },
      question: 'Do you like coffee?',
    },
    takeaways: [
      'Do/Does + sujeito + verbo básico para perguntar.',
      'Don\'t/Doesn\'t + verbo básico para negar.',
      'O verbo to be não usa do/does.',
    ],
  },
  {
    id: 'prepositions',
    level: 'basic',
    order: 8,
    title: 'Preposições de tempo e lugar: in, on, at',
    topic: 'Prepositions: in, on, at',
    summary: 'Saiba quando usar in, on e at com datas, horários e lugares.',
    estimatedMinutes: 9,
    skillTags: ['prepositions'],
    objectives: [
      'Usar in, on e at com tempo',
      'Usar in, on e at com lugares',
      'Evitar a tradução literal de "em"',
    ],
    explanation: [
      {
        pt: 'Tempo: "in" para meses, anos e partes do dia (in May, in 2025, in the morning); "on" para dias e datas (on Monday, on May 5th); "at" para horários (at 7 o\'clock, at night).',
        en: 'Time: "in" for months, years and parts of the day; "on" for days and dates; "at" for clock times and "at night".',
      },
      {
        pt: 'Lugar: "in" para dentro de algo, cidades e países (in the box, in Brazil); "on" para superfícies (on the table); "at" para pontos específicos (at the bus stop, at work, at home).',
        en: 'Place: "in" for inside something, cities and countries; "on" for surfaces; "at" for specific points (at the bus stop, at work, at home).',
      },
      {
        pt: 'Dica: pense em uma pirâmide invertida — "in" é o mais amplo, "on" é intermediário e "at" é o mais específico.',
        en: 'Tip: think of an upside-down pyramid — "in" is the widest, "on" is in the middle and "at" is the most specific.',
      },
    ],
    alternativeExplanations: [
      {
        pt: 'Em português tudo vira "em", mas em inglês a pergunta é: é um período grande (in), um dia (on) ou um ponto exato (at)? Para lugares: dentro (in), em cima (on) ou um ponto no mapa (at).',
        en: 'Ask yourself: is it a big period (in), a day (on) or an exact point (at)? For places: inside (in), on a surface (on) or a point on the map (at).',
      },
      {
        pt: 'Memorize três expressões fixas que não seguem a lógica: at home, at work, at night.',
        en: 'Memorize three fixed expressions: at home, at work, at night.',
      },
    ],
    table: {
      caption: 'in · on · at',
      headers: ['', 'Tempo', 'Lugar'],
      rows: [
        ['in', 'in July, in 2020, in the morning', 'in Brazil, in the kitchen'],
        ['on', 'on Monday, on my birthday', 'on the table, on the wall'],
        ['at', 'at 8 p.m., at night', 'at home, at work, at the door'],
      ],
    },
    examples: [
      { en: 'The meeting is on Monday at 10.', pt: 'A reunião é na segunda às 10.', highlight: 'on Monday' },
      { en: 'I was born in 1998.', pt: 'Eu nasci em 1998.', highlight: 'in 1998' },
      { en: "I'm at home now.", pt: 'Estou em casa agora.', highlight: 'at home' },
    ],
    extraExamples: [
      { en: 'There is a picture on the wall.', pt: 'Há um quadro na parede.', highlight: 'on the wall' },
      { en: 'We have lunch at noon.', pt: 'Nós almoçamos ao meio-dia.', highlight: 'at noon' },
      { en: 'She lives in Curitiba.', pt: 'Ela mora em Curitiba.', highlight: 'in Curitiba' },
    ],
    vocabularyIds: ['weekend', 'morning', 'night', 'kitchen', 'table'],
    exercises: [
      {
        id: 'prepositions-1',
        lessonId: 'prepositions',
        type: 'select_word',
        instruction: 'Selecione a preposição correta.',
        prompt: 'The meeting is ___ Monday.',
        options: ['on', 'in', 'at', 'to'],
        acceptedAnswers: ['on'],
        explanation: {
          pt: 'Para dias da semana usamos "on": on Monday, on Friday.',
          en: 'We use "on" with days of the week.',
        },
        skillTag: 'prepositions',
      },
      {
        id: 'prepositions-2',
        lessonId: 'prepositions',
        type: 'select_word',
        instruction: 'Selecione a preposição correta.',
        prompt: 'I was born ___ 1998.',
        options: ['in', 'on', 'at', 'to'],
        acceptedAnswers: ['in'],
        explanation: {
          pt: 'Para anos (e meses) usamos "in": in 1998, in May.',
          en: 'We use "in" with years and months.',
        },
        skillTag: 'prepositions',
      },
      {
        id: 'prepositions-3',
        lessonId: 'prepositions',
        type: 'select_word',
        instruction: 'Selecione a preposição correta.',
        prompt: "Let's meet ___ 7 p.m.",
        options: ['at', 'in', 'on', 'to'],
        acceptedAnswers: ['at'],
        explanation: {
          pt: 'Para horários exatos usamos "at": at 7 p.m.',
          en: 'We use "at" with clock times.',
        },
        skillTag: 'prepositions',
      },
      {
        id: 'prepositions-4',
        lessonId: 'prepositions',
        type: 'fill_blank',
        instruction: 'Complete com a preposição correta.',
        prompt: 'Your keys are ___ the table.',
        acceptedAnswers: ['on'],
        explanation: {
          pt: 'Para coisas sobre uma superfície usamos "on": on the table.',
          en: 'We use "on" for things on a surface.',
        },
        skillTag: 'prepositions',
      },
      {
        id: 'prepositions-5',
        lessonId: 'prepositions',
        type: 'multiple_choice',
        instruction: 'Escolha a frase correta.',
        prompt: 'Qual frase está correta?',
        options: [
          'I work at home on Fridays.',
          'I work in home in Fridays.',
          'I work at home in Fridays.',
          'I work on home at Fridays.',
        ],
        acceptedAnswers: ['I work at home on Fridays.'],
        explanation: {
          pt: '"At home" é uma expressão fixa, e dias da semana usam "on": at home on Fridays.',
          en: '"At home" is a fixed expression, and days use "on".',
        },
        skillTag: 'prepositions',
      },
      {
        id: 'prepositions-6',
        lessonId: 'prepositions',
        type: 'translate',
        instruction: 'Traduza para o inglês.',
        prompt: 'Eu estudo à noite.',
        acceptedAnswers: ['I study at night.'],
        explanation: {
          pt: '"À noite" é "at night" — uma das expressões fixas com "at".',
          en: '"At night" is a fixed expression.',
          tip: { pt: 'Mas: in the morning, in the afternoon, in the evening.', en: 'But: in the morning, in the afternoon, in the evening.' },
        },
        skillTag: 'prepositions',
      },
    ],
    practice: {
      opener: {
        en: "Let's practice in, on and at! I'm {assistant}. What do you usually do on weekends?",
        pt: 'Vamos praticar in, on e at! Eu sou {assistant}. O que você costuma fazer nos fins de semana?',
      },
      question: 'What do you usually do on weekends?',
    },
    takeaways: [
      'in: meses, anos, partes do dia, cidades e países.',
      'on: dias, datas e superfícies.',
      'at: horários e pontos específicos (at home, at work, at night).',
    ],
  },
  {
    id: 'simple-past',
    level: 'basic',
    order: 9,
    title: 'Passado simples',
    topic: 'Simple Past',
    summary: 'Conte o que você fez ontem, com verbos regulares e irregulares.',
    estimatedMinutes: 11,
    skillTags: ['simple_past'],
    objectives: [
      'Formar o passado de verbos regulares (-ed)',
      'Reconhecer verbos irregulares comuns',
      'Fazer perguntas e negativas com did',
    ],
    explanation: [
      {
        pt: 'Usamos o passado simples para ações que começaram e terminaram no passado: I visited my grandmother yesterday.',
        en: 'We use the simple past for finished actions in the past: I visited my grandmother yesterday.',
      },
      {
        pt: 'Verbos regulares recebem -ed: work → worked, play → played, study → studied.',
        en: 'Regular verbs take -ed: work → worked, play → played, study → studied.',
      },
      {
        pt: 'Muitos verbos comuns são irregulares e precisam ser memorizados: go → went, have → had, see → saw, eat → ate, buy → bought.',
        en: 'Many common verbs are irregular: go → went, have → had, see → saw, eat → ate, buy → bought.',
      },
      {
        pt: 'Na negativa e na pergunta usamos "did", e o verbo volta para a forma básica: I didn\'t go. Did you see it?',
        en: "In negatives and questions we use \"did\" and the base verb: I didn't go. Did you see it?",
      },
    ],
    alternativeExplanations: [
      {
        pt: 'O passado aparece uma vez só na frase. Se o "did" já está lá, o verbo não precisa mudar: Did you go? (e não "Did you went?").',
        en: 'The past appears only once in the sentence. If "did" is there, the verb stays the same: Did you go?',
      },
      {
        pt: 'Comece pelos 10 irregulares mais usados: went, had, did, said, got, made, saw, came, took, ate. Eles aparecem em quase toda conversa sobre o passado.',
        en: 'Start with the 10 most common irregular verbs: went, had, did, said, got, made, saw, came, took, ate.',
      },
    ],
    table: {
      caption: 'Verbos no passado',
      headers: ['Base', 'Passado', 'Português'],
      rows: [
        ['work', 'worked', 'trabalhar'],
        ['study', 'studied', 'estudar'],
        ['go', 'went', 'ir'],
        ['have', 'had', 'ter'],
        ['see', 'saw', 'ver'],
        ['eat', 'ate', 'comer'],
        ['buy', 'bought', 'comprar'],
      ],
    },
    examples: [
      { en: 'I watched a movie last night.', pt: 'Eu assisti a um filme ontem à noite.', highlight: 'watched' },
      { en: 'We went to the beach on Sunday.', pt: 'Nós fomos à praia no domingo.', highlight: 'went' },
      { en: "She didn't call me.", pt: 'Ela não me ligou.', highlight: "didn't call" },
      { en: 'Did you have lunch?', pt: 'Você almoçou?', highlight: 'Did you have' },
    ],
    extraExamples: [
      { en: 'They bought a new car last year.', pt: 'Eles compraram um carro novo ano passado.', highlight: 'bought' },
      { en: 'I studied for three hours yesterday.', pt: 'Eu estudei por três horas ontem.', highlight: 'studied' },
      { en: "We didn't see the game.", pt: 'Nós não vimos o jogo.', highlight: "didn't see" },
    ],
    vocabularyIds: ['yesterday', 'last-weekend', 'visit', 'buy'],
    exercises: [
      {
        id: 'past-1',
        lessonId: 'simple-past',
        type: 'select_word',
        instruction: 'Selecione o verbo no passado.',
        prompt: 'Yesterday I ___ a great movie.',
        options: ['saw', 'see', 'seen', 'sees'],
        acceptedAnswers: ['saw'],
        explanation: {
          pt: '"See" é irregular: o passado é "saw". "Seen" é o particípio (usado em outros tempos verbais).',
          en: '"See" is irregular: the past is "saw". "Seen" is the past participle.',
        },
        skillTag: 'simple_past',
      },
      {
        id: 'past-2',
        lessonId: 'simple-past',
        type: 'fill_blank',
        instruction: 'Complete com o verbo "go" no passado.',
        prompt: 'We ___ to the beach last weekend.',
        acceptedAnswers: ['went'],
        explanation: {
          pt: '"Go" é irregular: o passado é "went".',
          en: '"Go" is irregular: the past is "went".',
        },
        skillTag: 'simple_past',
      },
      {
        id: 'past-3',
        lessonId: 'simple-past',
        type: 'multiple_choice',
        instruction: 'Escolha a frase correta.',
        prompt: 'Qual frase está correta?',
        options: [
          "I didn't go to work yesterday.",
          "I didn't went to work yesterday.",
          "I don't went to work yesterday.",
          'I not go to work yesterday.',
        ],
        acceptedAnswers: ["I didn't go to work yesterday."],
        explanation: {
          pt: 'Depois de "didn\'t", o verbo fica na forma básica (go), porque o "did" já indica o passado.',
          en: "After \"didn't\", use the base verb (go) — \"did\" already shows the past.",
        },
        skillTag: 'simple_past',
      },
      {
        id: 'past-4',
        lessonId: 'simple-past',
        type: 'select_word',
        instruction: 'Selecione o auxiliar correto.',
        prompt: '___ you call your mom last night?',
        options: ['Did', 'Do', 'Does', 'Were'],
        acceptedAnswers: ['Did'],
        explanation: {
          pt: 'Perguntas no passado simples usam "did": Did you call…?',
          en: 'Simple past questions use "did".',
        },
        skillTag: 'simple_past',
      },
      {
        id: 'past-5',
        lessonId: 'simple-past',
        type: 'translate',
        instruction: 'Traduza para o inglês.',
        prompt: 'Ela estudou muito ontem.',
        acceptedAnswers: ['She studied a lot yesterday.', 'She studied hard yesterday.', 'Yesterday she studied a lot.'],
        explanation: {
          pt: '"Study" no passado é "studied" (o y vira -ied). "Muito" pode ser "a lot" ou "hard".',
          en: '"Study" in the past is "studied". "A lot" or "hard" both work.',
        },
        skillTag: 'simple_past',
      },
      {
        id: 'past-6',
        lessonId: 'simple-past',
        type: 'write',
        instruction: 'Escreva uma frase sobre o que você fez ontem.',
        prompt: 'What did you do yesterday?',
        acceptedAnswers: [],
        requirements: [
          {
            pattern:
              '\\b\\w+ed\\b|\\b(went|had|saw|ate|bought|made|took|came|got|did|was|were|met|read|wrote|spoke|drank|slept|left|felt|ran|swam|watched|played)\\b',
            message: 'Use um verbo no passado (ex.: worked, went, had).',
          },
        ],
        minWords: 3,
        explanation: {
          pt: 'No passado simples, use -ed nos verbos regulares (worked) e a forma irregular nos outros (went, had, saw).',
          en: 'Use -ed for regular verbs (worked) and the irregular form for the others (went, had, saw).',
        },
        skillTag: 'simple_past',
      },
    ],
    practice: {
      opener: {
        en: "Let's talk about the past! I'm {assistant}. What did you do last weekend?",
        pt: 'Vamos falar do passado! Eu sou {assistant}. O que você fez no último fim de semana?',
      },
      question: 'What did you do last weekend?',
    },
    takeaways: [
      'Regulares: -ed (worked, studied).',
      'Irregulares comuns: went, had, saw, ate, bought.',
      'Com did/didn\'t, o verbo volta à forma básica.',
    ],
  },
  {
    id: 'future',
    level: 'basic',
    order: 10,
    title: 'Futuro com will e going to',
    topic: 'Future: will & going to',
    summary: 'Fale de planos, decisões e previsões.',
    estimatedMinutes: 9,
    skillTags: ['future'],
    objectives: [
      'Usar "going to" para planos',
      'Usar "will" para decisões rápidas, promessas e previsões',
      'Formar negativas (won\'t / not going to)',
    ],
    explanation: [
      {
        pt: '"Going to" é usado para planos e intenções já decididos: I\'m going to travel in July.',
        en: "\"Going to\" is for plans and intentions you have already decided: I'm going to travel in July.",
      },
      {
        pt: '"Will" é usado para decisões no momento da fala, promessas e previsões: I\'ll help you! It will rain tomorrow.',
        en: "\"Will\" is for decisions made while speaking, promises and predictions: I'll help you!",
      },
      {
        pt: 'Estruturas: sujeito + will + verbo básico (She will call). Sujeito + am/is/are + going to + verbo básico (They are going to study).',
        en: 'Structures: subject + will + base verb. Subject + am/is/are + going to + base verb.',
      },
    ],
    alternativeExplanations: [
      {
        pt: '"Going to" = já está na agenda. "Will" = acabei de decidir ou estou prometendo. "Vou viajar em julho (já comprei a passagem)" → going to. "Eu atendo!" (o telefone tocou agora) → I\'ll get it!',
        en: '"Going to" = it is already in your plans. "Will" = you just decided or you are promising.',
      },
      {
        pt: 'Depois de "will" nunca vem "to" nem -s: She will call (e não "will to call" ou "will calls").',
        en: 'After "will", never use "to" or -s: She will call.',
      },
    ],
    table: {
      caption: 'will × going to',
      headers: ['Uso', 'Exemplo'],
      rows: [
        ['Plano decidido', "I'm going to visit my parents."],
        ['Decisão na hora', "I'll have a coffee, please."],
        ['Promessa', "I won't forget!"],
        ['Previsão com evidência', "Look at the clouds! It's going to rain."],
      ],
    },
    examples: [
      { en: "I'm going to start a new course next month.", pt: 'Vou começar um curso novo no mês que vem.', highlight: 'going to start' },
      { en: "I'll call you later.", pt: 'Eu te ligo mais tarde.', highlight: "I'll call" },
      { en: "We won't be late.", pt: 'Nós não vamos nos atrasar.', highlight: "won't" },
    ],
    extraExamples: [
      { en: 'She is going to buy a new laptop.', pt: 'Ela vai comprar um notebook novo.', highlight: 'is going to buy' },
      { en: 'I think it will be a great day.', pt: 'Acho que vai ser um ótimo dia.', highlight: 'will be' },
      { en: 'Are you going to watch the game?', pt: 'Você vai assistir ao jogo?', highlight: 'going to watch' },
    ],
    vocabularyIds: ['tomorrow', 'next-week', 'plan', 'travel'],
    exercises: [
      {
        id: 'future-1',
        lessonId: 'future',
        type: 'select_word',
        instruction: 'Selecione a forma correta.',
        prompt: 'Look at those clouds! It ___ rain.',
        options: ['is going to', 'going to', 'will to', 'is go to'],
        acceptedAnswers: ['is going to'],
        explanation: {
          pt: 'Para previsões com evidência (as nuvens), usamos "going to" com o verbo to be: It is going to rain.',
          en: 'For predictions based on evidence, use "be going to": It is going to rain.',
        },
        skillTag: 'future',
      },
      {
        id: 'future-2',
        lessonId: 'future',
        type: 'select_word',
        instruction: 'Selecione a forma correta.',
        prompt: "I'm tired. I think I ___ go to bed early.",
        options: ['will', 'am', 'going', 'do'],
        acceptedAnswers: ['will'],
        explanation: {
          pt: 'Uma decisão tomada na hora usa "will": I think I will go to bed early.',
          en: 'A decision made at the moment uses "will".',
        },
        skillTag: 'future',
      },
      {
        id: 'future-3',
        lessonId: 'future',
        type: 'fill_blank',
        instruction: 'Complete a frase.',
        prompt: 'We are ___ to visit our friends next weekend.',
        acceptedAnswers: ['going'],
        explanation: {
          pt: 'A estrutura é "be + going to + verbo": We are going to visit…',
          en: 'The structure is "be + going to + verb".',
        },
        skillTag: 'future',
      },
      {
        id: 'future-4',
        lessonId: 'future',
        type: 'multiple_choice',
        instruction: 'Escolha a frase correta.',
        prompt: 'Qual frase está correta?',
        options: ['She will call you later.', 'She will calls you later.', 'She wills call you later.', 'She will to call you later.'],
        acceptedAnswers: ['She will call you later.'],
        explanation: {
          pt: 'Depois de "will", o verbo fica na forma básica, sem -s e sem "to".',
          en: 'After "will", use the base verb — no -s and no "to".',
        },
        skillTag: 'future',
      },
      {
        id: 'future-5',
        lessonId: 'future',
        type: 'translate',
        instruction: 'Traduza para o inglês.',
        prompt: 'Eu vou viajar amanhã.',
        acceptedAnswers: [
          "I'm going to travel tomorrow.",
          'I am going to travel tomorrow.',
          'I will travel tomorrow.',
          "I'll travel tomorrow.",
        ],
        explanation: {
          pt: 'Para um plano, "going to" é o mais natural: I\'m going to travel tomorrow. "I will travel" também é aceito.',
          en: "For a plan, \"going to\" is most natural: I'm going to travel tomorrow.",
        },
        skillTag: 'future',
      },
    ],
    practice: {
      opener: {
        en: "Let's talk about plans! I'm {assistant}. What are you going to do this weekend?",
        pt: 'Vamos falar de planos! Eu sou {assistant}. O que você vai fazer neste fim de semana?',
      },
      question: 'What are you going to do this weekend?',
    },
    takeaways: [
      'Going to: planos já decididos.',
      'Will: decisões na hora, promessas e previsões.',
      'Depois de will: verbo básico (will call).',
    ],
  },
];
