import type { Lesson } from '../../domain/content';

/** Aulas do nível Iniciante (Análise de requisitos §15). */
export const beginnerLessons: Lesson[] = [
  {
    id: 'greetings',
    level: 'beginner',
    order: 1,
    title: 'Cumprimentos e apresentações',
    topic: 'Greetings & introductions',
    summary: 'Diga olá, apresente-se e pergunte o nome de alguém.',
    estimatedMinutes: 8,
    skillTags: ['greetings'],
    objectives: [
      'Cumprimentar em situações formais e informais',
      'Dizer seu nome e perguntar o nome de alguém',
      'Despedir-se de forma natural',
    ],
    explanation: [
      {
        pt: '"Hello" funciona em qualquer situação. "Hi" e "Hey" são mais informais — use com amigos e colegas.',
        en: '"Hello" works in any situation. "Hi" and "Hey" are more informal — use them with friends and colleagues.',
      },
      {
        pt: 'Para cumprimentar conforme o horário, use "Good morning" (manhã), "Good afternoon" (tarde) e "Good evening" (ao chegar, à noite). "Good night" é usado só para se despedir ou antes de dormir.',
        en: 'Use "Good morning", "Good afternoon" and "Good evening" depending on the time of day. "Good night" is only for saying goodbye or before going to bed.',
      },
      {
        pt: 'Para se apresentar, diga "My name is Ana" ou "I\'m Ana". Para perguntar, "What\'s your name?". Ao conhecer alguém, "Nice to meet you!".',
        en: 'To introduce yourself, say "My name is Ana" or "I\'m Ana". To ask, "What\'s your name?". When you meet someone, "Nice to meet you!".',
      },
    ],
    alternativeExplanations: [
      {
        pt: 'Pense assim: "Hello" é o "Olá" (serve sempre) e "Hi" é o "Oi" (mais casual). "Good night" é o "boa noite" de quem está indo embora — para chegar à noite, diga "Good evening".',
        en: 'Think of it like this: "Hello" always works and "Hi" is casual. "Good night" is for leaving — when you arrive in the evening, say "Good evening".',
      },
      {
        pt: 'Uma apresentação completa tem três partes: cumprimento + nome + frase simpática. Exemplo: "Hi! I\'m Leo. Nice to meet you!"',
        en: 'A complete introduction has three parts: greeting + name + a friendly phrase. Example: "Hi! I\'m Leo. Nice to meet you!"',
      },
    ],
    table: {
      caption: 'Cumprimentos por situação',
      headers: ['Inglês', 'Quando usar', 'Português'],
      rows: [
        ['Hello', 'Qualquer situação', 'Olá'],
        ['Hi / Hey', 'Informal', 'Oi'],
        ['Good morning', 'Até o meio-dia', 'Bom dia'],
        ['Good afternoon', 'À tarde', 'Boa tarde'],
        ['Good evening', 'Ao chegar, à noite', 'Boa noite'],
        ['Good night', 'Ao sair ou dormir', 'Boa noite'],
      ],
    },
    examples: [
      { en: 'Hi! My name is Ana.', pt: 'Oi! Meu nome é Ana.', highlight: 'My name is' },
      { en: "What's your name?", pt: 'Qual é o seu nome?', highlight: "What's your name" },
      { en: 'Nice to meet you!', pt: 'Prazer em conhecer você!', highlight: 'Nice to meet you' },
      { en: 'See you tomorrow!', pt: 'Até amanhã!', highlight: 'See you' },
    ],
    extraExamples: [
      { en: 'Good morning, everyone!', pt: 'Bom dia, pessoal!', highlight: 'Good morning' },
      { en: "Hey! I'm Carlos. I'm new here.", pt: 'Oi! Eu sou o Carlos. Sou novo aqui.', highlight: "I'm Carlos" },
      { en: 'Good night! See you later.', pt: 'Boa noite! Até mais.', highlight: 'Good night' },
    ],
    vocabularyIds: ['hello', 'good-morning', 'good-evening', 'nice-to-meet-you', 'see-you-later'],
    exercises: [
      {
        id: 'greetings-1',
        lessonId: 'greetings',
        type: 'multiple_choice',
        instruction: 'Escolha o cumprimento adequado.',
        prompt: 'Você chega a uma reunião às 9h da manhã. O que você diz?',
        options: ['Good morning!', 'Good night!', 'Goodbye!', 'Good evening!'],
        acceptedAnswers: ['Good morning!'],
        explanation: {
          pt: '"Good morning" é usado pela manhã, até por volta do meio-dia. "Good night" serve apenas para se despedir à noite.',
          en: '"Good morning" is used until about noon. "Good night" is only for saying goodbye at night.',
        },
        skillTag: 'greetings',
      },
      {
        id: 'greetings-2',
        lessonId: 'greetings',
        type: 'select_word',
        instruction: 'Selecione a palavra que completa a frase.',
        prompt: 'Hi! My ___ is Carlos.',
        options: ['name', 'names', 'call', 'am'],
        acceptedAnswers: ['name'],
        explanation: {
          pt: 'A estrutura é "My name is…" (Meu nome é…). "Name" fica no singular porque é um nome só.',
          en: 'The structure is "My name is…". "Name" is singular because it is one name.',
          tip: { pt: 'Outra forma comum é "I\'m Carlos".', en: 'Another common way is "I\'m Carlos".' },
        },
        skillTag: 'greetings',
      },
      {
        id: 'greetings-3',
        lessonId: 'greetings',
        type: 'fill_blank',
        instruction: 'Complete a frase.',
        prompt: 'Nice to ___ you!',
        acceptedAnswers: ['meet'],
        hint: 'Significa "conhecer". Começa com "m".',
        explanation: {
          pt: '"Nice to meet you" significa "Prazer em conhecer você". O verbo "meet" significa conhecer ou encontrar alguém.',
          en: '"Nice to meet you" is what we say when we meet someone for the first time.',
        },
        skillTag: 'greetings',
      },
      {
        id: 'greetings-4',
        lessonId: 'greetings',
        type: 'translate',
        instruction: 'Traduza para o inglês.',
        prompt: 'Qual é o seu nome?',
        acceptedAnswers: ["What's your name?", 'What is your name?'],
        explanation: {
          pt: 'A pergunta começa com "What" (qual/o que): "What\'s your name?". "What\'s" é a forma curta de "What is".',
          en: 'The question starts with "What": "What\'s your name?". "What\'s" is the short form of "What is".',
        },
        skillTag: 'greetings',
      },
      {
        id: 'greetings-5',
        lessonId: 'greetings',
        type: 'multiple_choice',
        instruction: 'Escolha a melhor opção.',
        prompt: 'Você está saindo de uma festa às 23h. O que você diz?',
        options: ['Good night!', 'Good evening!', 'Good afternoon!', 'Good morning!'],
        acceptedAnswers: ['Good night!'],
        explanation: {
          pt: 'Ao se despedir à noite, usamos "Good night". "Good evening" é para quando você chega.',
          en: 'When you leave at night, say "Good night". "Good evening" is for when you arrive.',
        },
        skillTag: 'greetings',
      },
    ],
    practice: {
      opener: {
        en: "Let's practice! Hi, I'm {assistant}. What's your name?",
        pt: 'Vamos praticar! Oi, eu sou {assistant}. Qual é o seu nome?',
      },
      question: "What's your name?",
    },
    takeaways: [
      '"Hello" serve para qualquer situação; "Hi" é mais informal.',
      '"Good night" é para despedidas — ao chegar à noite, use "Good evening".',
      'Apresente-se com "My name is…" ou "I\'m…".',
    ],
  },
  {
    id: 'alphabet',
    level: 'beginner',
    order: 2,
    title: 'O alfabeto e como soletrar',
    topic: 'The alphabet & spelling',
    summary: 'Reconheça as letras em inglês e soletre seu nome.',
    estimatedMinutes: 7,
    skillTags: ['alphabet'],
    objectives: [
      'Reconhecer os sons das vogais em inglês',
      'Evitar as confusões mais comuns (E/I, G/J)',
      'Soletrar seu nome e pedir que alguém soletre',
    ],
    explanation: [
      {
        pt: 'As letras têm nomes diferentes do português. As vogais são as que mais confundem: A soa como "êi", E como "í", I como "ái", O como "ôu" e U como "iú".',
        en: 'Letter names are different from Portuguese. Vowels are the trickiest: A sounds like "ay", E like "ee", I like "eye", O like "oh" and U like "you".',
      },
      {
        pt: 'Pares que costumam confundir brasileiros: E ("í") e I ("ái"); G ("djí") e J ("djêi"). Vale a pena praticar esses quatro.',
        en: 'Common confusions for Brazilian learners: E and I; G and J. Practice these four letters.',
      },
      {
        pt: 'Para pedir que alguém soletre: "How do you spell that?". Letras repetidas são ditas com "double": Anna = A, double N, A.',
        en: 'To ask someone to spell a word: "How do you spell that?". Repeated letters use "double": Anna = A, double N, A.',
      },
    ],
    alternativeExplanations: [
      {
        pt: 'Um truque: o nome da letra I em inglês soa como a palavra "eye" (olho), e o nome da letra E soa como o "i" do português.',
        en: 'A trick: the letter I sounds like the word "eye", and the letter E sounds like the Portuguese "i".',
      },
      {
        pt: 'Soletrar é útil em ligações, cadastros e e-mails. Pratique com o seu nome completo — é a palavra que você mais vai soletrar!',
        en: 'Spelling is useful on the phone, in forms and e-mails. Practice with your full name — it is the word you will spell the most!',
      },
    ],
    table: {
      caption: 'Pronúncia aproximada (apenas indicação escrita)',
      headers: ['Letra', 'Soa como', 'Atenção'],
      rows: [
        ['A', 'êi', 'como em "day"'],
        ['E', 'í', 'não é "é"'],
        ['I', 'ái', 'como "eye"'],
        ['O', 'ôu', 'como em "go"'],
        ['U', 'iú', 'como "you"'],
        ['G', 'djí', 'não confunda com J'],
        ['J', 'djêi', 'não confunda com G'],
        ['R', 'ár', ''],
        ['Y', 'uái', 'como "why"'],
      ],
    },
    examples: [
      { en: 'How do you spell your name?', pt: 'Como se soletra o seu nome?', highlight: 'spell' },
      { en: "It's M-A-R-I-A.", pt: 'É M-A-R-I-A.' },
      { en: 'Anna — A, double N, A.', pt: 'Anna — A, dois N, A.', highlight: 'double N' },
    ],
    extraExamples: [
      { en: 'Can you spell that, please?', pt: 'Você pode soletrar, por favor?', highlight: 'spell' },
      { en: 'My e-mail is ana at gmail dot com.', pt: 'Meu e-mail é ana arroba gmail ponto com.', highlight: 'at' },
      { en: 'Is that with a G or a J?', pt: 'É com G ou com J?' },
    ],
    vocabularyIds: ['spell', 'letter'],
    exercises: [
      {
        id: 'alphabet-1',
        lessonId: 'alphabet',
        type: 'multiple_choice',
        instruction: 'Escolha a resposta correta.',
        prompt: 'Qual letra soa como "ái" em inglês?',
        options: ['I', 'E', 'A', 'Y'],
        acceptedAnswers: ['I'],
        explanation: {
          pt: 'Em inglês, a letra I soa como "ái" (igual à palavra "eye"). A letra E é que soa como "í".',
          en: 'The letter I sounds like "eye". The letter E sounds like "ee".',
        },
        skillTag: 'alphabet',
      },
      {
        id: 'alphabet-2',
        lessonId: 'alphabet',
        type: 'multiple_choice',
        instruction: 'Escolha a resposta correta.',
        prompt: 'Qual letra soa como "í" em inglês?',
        options: ['E', 'I', 'Y', 'A'],
        acceptedAnswers: ['E'],
        explanation: {
          pt: 'A letra E soa como "í". É o contrário do que muitos brasileiros esperam, por isso vale praticar!',
          en: 'The letter E sounds like "ee". Many learners expect the opposite, so it is worth practicing!',
        },
        skillTag: 'alphabet',
      },
      {
        id: 'alphabet-3',
        lessonId: 'alphabet',
        type: 'fill_blank',
        instruction: 'Complete a pergunta.',
        prompt: 'How do you ___ your name?',
        acceptedAnswers: ['spell'],
        hint: 'Verbo que significa "soletrar".',
        explanation: {
          pt: '"Spell" significa soletrar. A pergunta completa é "How do you spell your name?".',
          en: '"Spell" means to say the letters of a word in order.',
        },
        skillTag: 'alphabet',
      },
      {
        id: 'alphabet-4',
        lessonId: 'alphabet',
        type: 'select_word',
        instruction: 'Selecione a palavra correta.',
        prompt: 'My name is Anna, with ___ N.',
        options: ['double', 'two', 'twice', 'pair'],
        acceptedAnswers: ['double'],
        explanation: {
          pt: 'Para letras repetidas, dizemos "double": A, double N, A.',
          en: 'For repeated letters, we say "double": A, double N, A.',
        },
        skillTag: 'alphabet',
      },
      {
        id: 'alphabet-5',
        lessonId: 'alphabet',
        type: 'translate',
        instruction: 'Traduza para o inglês.',
        prompt: 'Como se soletra isso?',
        acceptedAnswers: ['How do you spell that?', 'How do you spell it?', 'How do you spell this?', 'How is that spelled?'],
        explanation: {
          pt: 'Usamos "How do you spell…?" para pedir que alguém soletre: "How do you spell that?".',
          en: 'We use "How do you spell…?" to ask someone to spell a word.',
        },
        skillTag: 'alphabet',
      },
    ],
    practice: {
      opener: {
        en: "Let's practice spelling! My name is {assistant}. How do you spell your name?",
        pt: 'Vamos praticar a soletração! Meu nome é {assistant}. Como se soletra o seu nome?',
      },
      question: 'How do you spell your name?',
    },
    takeaways: [
      'E soa como "í" e I soa como "ái".',
      'Use "How do you spell…?" para pedir a soletração.',
      'Letras repetidas: "double" (double N, double L).',
    ],
  },
  {
    id: 'verb-to-be',
    level: 'beginner',
    order: 3,
    title: 'Verbo to be (ser e estar)',
    topic: 'Verb to be',
    summary: 'Use am, is e are para falar de você e dos outros.',
    estimatedMinutes: 10,
    skillTags: ['to_be'],
    objectives: [
      'Conjugar o verbo to be com todos os pronomes',
      'Usar as formas curtas (I\'m, she\'s, they\'re)',
      'Fazer negativas e perguntas',
    ],
    explanation: [
      {
        pt: 'O verbo "to be" significa ser ou estar. Ele muda conforme a pessoa: I am, you are, he/she/it is, we are, they are.',
        en: 'The verb "to be" changes with the subject: I am, you are, he/she/it is, we are, they are.',
      },
      {
        pt: 'Na fala, as formas curtas são muito comuns: I\'m, you\'re, he\'s, she\'s, it\'s, we\'re, they\'re.',
        en: "Short forms are very common in speech: I'm, you're, he's, she's, it's, we're, they're.",
      },
      {
        pt: 'Negativa: coloque "not" depois do verbo — I\'m not tired, she isn\'t here. Pergunta: inverta a ordem — Are you ready? Is he your brother?',
        en: "Negative: add \"not\" after the verb — I'm not tired, she isn't here. Question: change the order — Are you ready? Is he your brother?",
      },
      {
        pt: 'Em inglês, o sujeito é obrigatório. Em português dizemos "Está feliz", mas em inglês é "He is happy" ou "She is happy".',
        en: 'In English, the subject is always required: "He is happy", never just "Is happy".',
      },
    ],
    alternativeExplanations: [
      {
        pt: 'Pense em três "caixinhas": "am" só combina com I; "is" combina com uma pessoa ou coisa (he, she, it, my mom, the car); "are" combina com you e com o plural (we, they, my friends).',
        en: 'Think of three boxes: "am" only goes with I; "is" goes with one person or thing (he, she, it); "are" goes with you and plurals (we, they).',
      },
      {
        pt: 'O mesmo verbo serve para "ser" e "estar": "I am a teacher" (sou professor) e "I am tired" (estou cansado). O contexto mostra o sentido.',
        en: 'The same verb covers two Portuguese verbs, "ser" and "estar": "I am a teacher" and "I am tired". Context shows the meaning.',
      },
    ],
    table: {
      caption: 'Verbo to be no presente',
      headers: ['Pronome', 'Forma completa', 'Forma curta', 'Português'],
      rows: [
        ['I', 'I am', "I'm", 'eu sou/estou'],
        ['You', 'You are', "You're", 'você é/está'],
        ['He', 'He is', "He's", 'ele é/está'],
        ['She', 'She is', "She's", 'ela é/está'],
        ['It', 'It is', "It's", 'é/está (coisas, animais)'],
        ['We', 'We are', "We're", 'nós somos/estamos'],
        ['They', 'They are', "They're", 'eles/elas são/estão'],
      ],
    },
    examples: [
      { en: "I'm a student.", pt: 'Eu sou estudante.', highlight: "I'm" },
      { en: 'She is my sister.', pt: 'Ela é minha irmã.', highlight: 'is' },
      { en: "We aren't tired.", pt: 'Nós não estamos cansados.', highlight: "aren't" },
      { en: 'Are you ready?', pt: 'Você está pronto?', highlight: 'Are you' },
    ],
    extraExamples: [
      { en: "It's cold today.", pt: 'Está frio hoje.', highlight: "It's" },
      { en: 'They are from Recife.', pt: 'Eles são de Recife.', highlight: 'are' },
      { en: 'Is he your teacher?', pt: 'Ele é seu professor?', highlight: 'Is he' },
    ],
    vocabularyIds: ['student', 'teacher', 'happy', 'tired', 'friend'],
    exercises: [
      {
        id: 'to-be-1',
        lessonId: 'verb-to-be',
        type: 'select_word',
        instruction: 'Selecione a forma correta do verbo to be.',
        prompt: 'She ___ my sister.',
        options: ['is', 'am', 'are', 'be'],
        acceptedAnswers: ['is'],
        explanation: {
          pt: 'Com he, she e it usamos "is": She is my sister.',
          en: 'With he, she and it we use "is": She is my sister.',
        },
        skillTag: 'to_be',
      },
      {
        id: 'to-be-2',
        lessonId: 'verb-to-be',
        type: 'select_word',
        instruction: 'Selecione a forma correta do verbo to be.',
        prompt: 'We ___ from Brazil.',
        options: ['are', 'is', 'am', 'be'],
        acceptedAnswers: ['are'],
        explanation: {
          pt: 'Com we, you e they usamos "are": We are from Brazil.',
          en: 'With we, you and they we use "are": We are from Brazil.',
        },
        skillTag: 'to_be',
      },
      {
        id: 'to-be-3',
        lessonId: 'verb-to-be',
        type: 'fill_blank',
        instruction: 'Complete com o verbo to be.',
        prompt: 'I ___ a student.',
        acceptedAnswers: ['am'],
        explanation: {
          pt: 'Com "I", o verbo to be é sempre "am": I am a student (ou I\'m a student).',
          en: "With \"I\", the verb to be is always \"am\": I am a student (or I'm a student).",
        },
        skillTag: 'to_be',
      },
      {
        id: 'to-be-4',
        lessonId: 'verb-to-be',
        type: 'multiple_choice',
        instruction: 'Escolha a forma negativa correta.',
        prompt: 'They ___ tired.',
        options: ['are not', 'not are', 'is not', "don't"],
        acceptedAnswers: ['are not'],
        explanation: {
          pt: 'Na negativa, o "not" vem depois do verbo to be: They are not (aren\'t) tired. Não usamos "don\'t" com o verbo to be.',
          en: "In the negative, \"not\" comes after the verb to be: They are not (aren't) tired. We don't use \"don't\" with the verb to be.",
        },
        skillTag: 'to_be',
      },
      {
        id: 'to-be-5',
        lessonId: 'verb-to-be',
        type: 'translate',
        instruction: 'Traduza para o inglês.',
        prompt: 'Ele está feliz.',
        acceptedAnswers: ['He is happy.', "He's happy."],
        explanation: {
          pt: '"Estar feliz" usa o verbo to be: He is happy. Em português podemos omitir o sujeito, mas em inglês o "he" é obrigatório.',
          en: '"To be happy" uses the verb to be: He is happy. The subject "he" is required.',
        },
        skillTag: 'to_be',
      },
      {
        id: 'to-be-6',
        lessonId: 'verb-to-be',
        type: 'write',
        instruction: 'Escreva uma frase se apresentando com o verbo to be (nome, idade, profissão ou cidade).',
        prompt: 'Introduce yourself using "I am" or "I\'m".',
        acceptedAnswers: [],
        requirements: [{ pattern: "\\b(i am|i'm)\\b", message: 'Use "I am" ou "I\'m" na sua frase.' }],
        minWords: 3,
        explanation: {
          pt: 'Com "I" usamos sempre "am": I am Ana / I\'m a designer / I\'m from Salvador.',
          en: "With \"I\" we always use \"am\": I am Ana / I'm a designer / I'm from Salvador.",
        },
        skillTag: 'to_be',
      },
    ],
    practice: {
      opener: {
        en: "Let's use the verb to be! I'm {assistant} and I'm your English assistant. Where are you from?",
        pt: 'Vamos usar o verbo to be! Eu sou {assistant}, sua assistente de inglês. De onde você é?',
      },
      question: 'Where are you from?',
    },
    takeaways: [
      'I am · you/we/they are · he/she/it is.',
      'Negativa: verbo + not (isn\'t, aren\'t, I\'m not).',
      'Pergunta: inverta a ordem (Are you…? Is she…?).',
    ],
  },
  {
    id: 'numbers-age',
    level: 'beginner',
    order: 4,
    title: 'Números e idade',
    topic: 'Numbers & age',
    summary: 'Conte, diga sua idade e pergunte a idade de alguém.',
    estimatedMinutes: 8,
    skillTags: ['numbers', 'to_be'],
    objectives: [
      'Diferenciar -teen (13–19) e -ty (20, 30, 40…)',
      'Dizer a idade com o verbo to be',
      'Perguntar "How old are you?"',
    ],
    explanation: [
      {
        pt: 'De 13 a 19 os números terminam em "-teen" (thirteen, fifteen). As dezenas terminam em "-ty" (thirty, fifty). Na fala, o "-teen" é mais forte e longo: fif-TEEN × FIF-ty.',
        en: 'Numbers 13–19 end in "-teen" (thirteen, fifteen). Tens end in "-ty" (thirty, fifty). In speech, stress "-teen": fif-TEEN vs. FIF-ty.',
      },
      {
        pt: 'Para dizer a idade, usamos o verbo to be, e não "have": I am 25 years old (ou só I\'m 25). "I have 25 years" é tradução literal do português e soa estranho em inglês.',
        en: 'To say your age, use the verb to be, not "have": I am 25 years old (or just I\'m 25).',
      },
      {
        pt: 'Para perguntar a idade: "How old are you?". Sobre outra pessoa: "How old is your brother?".',
        en: 'To ask about age: "How old are you?". About someone else: "How old is your brother?".',
      },
    ],
    alternativeExplanations: [
      {
        pt: 'Em inglês, a idade é algo que você "é", não algo que você "tem": I am 30 = "eu sou 30 (anos de idade)". Por isso usamos am/is/are.',
        en: 'In English, your age is something you "are", not something you "have": I am 30.',
      },
      {
        pt: 'Para não confundir 15 e 50: "fifteen" tem dois sons fortes no final (fif-TEEN); "fifty" tem a força no começo (FIF-ty).',
        en: 'To avoid mixing 15 and 50: "fifteen" is stressed at the end (fif-TEEN); "fifty" at the beginning (FIF-ty).',
      },
    ],
    table: {
      caption: 'Números importantes',
      headers: ['Número', 'Inglês', 'Número', 'Inglês'],
      rows: [
        ['1', 'one', '13', 'thirteen'],
        ['2', 'two', '15', 'fifteen'],
        ['3', 'three', '20', 'twenty'],
        ['10', 'ten', '30', 'thirty'],
        ['11', 'eleven', '50', 'fifty'],
        ['12', 'twelve', '100', 'one hundred'],
      ],
    },
    examples: [
      { en: "I'm 25 years old.", pt: 'Eu tenho 25 anos.', highlight: "I'm 25 years old" },
      { en: 'How old are you?', pt: 'Quantos anos você tem?', highlight: 'How old' },
      { en: 'My daughter is three.', pt: 'Minha filha tem três anos.', highlight: 'is three' },
    ],
    extraExamples: [
      { en: 'My grandmother is eighty years old.', pt: 'Minha avó tem oitenta anos.', highlight: 'is eighty years old' },
      { en: 'How old is your dog?', pt: 'Quantos anos tem o seu cachorro?', highlight: 'How old is' },
      { en: 'There are fifteen students in my class.', pt: 'Há quinze alunos na minha turma.', highlight: 'fifteen' },
    ],
    vocabularyIds: ['fifteen', 'thirty', 'years-old', 'number'],
    exercises: [
      {
        id: 'numbers-1',
        lessonId: 'numbers-age',
        type: 'multiple_choice',
        instruction: 'Escolha a resposta correta.',
        prompt: 'Como se escreve 15 em inglês?',
        options: ['fifteen', 'fifty', 'five', 'fiveteen'],
        acceptedAnswers: ['fifteen'],
        explanation: {
          pt: 'De 13 a 19 os números terminam em "-teen": thirteen, fourteen, fifteen… Já "fifty" é 50.',
          en: 'Numbers from 13 to 19 end in "-teen". "Fifty" is 50.',
        },
        skillTag: 'numbers',
      },
      {
        id: 'numbers-2',
        lessonId: 'numbers-age',
        type: 'select_word',
        instruction: 'Selecione a palavra correta.',
        prompt: 'I ___ 25 years old.',
        options: ['am', 'have', 'has', 'is'],
        acceptedAnswers: ['am'],
        explanation: {
          pt: 'A idade é expressa com o verbo to be: I am 25 years old. Em português dizemos "tenho 25 anos", mas em inglês não usamos "have" para idade.',
          en: 'Age uses the verb to be: I am 25 years old. We don\'t use "have" for age in English.',
          tip: { pt: 'Também é natural dizer apenas "I\'m 25".', en: 'It is also natural to say just "I\'m 25".' },
        },
        skillTag: 'to_be',
      },
      {
        id: 'numbers-3',
        lessonId: 'numbers-age',
        type: 'fill_blank',
        instruction: 'Complete a pergunta.',
        prompt: 'How ___ are you? — I\'m 30.',
        acceptedAnswers: ['old'],
        explanation: {
          pt: '"How old are you?" é a pergunta sobre idade (ao pé da letra, "quão velho você é?").',
          en: '"How old are you?" is how we ask someone\'s age.',
        },
        skillTag: 'numbers',
      },
      {
        id: 'numbers-4',
        lessonId: 'numbers-age',
        type: 'translate',
        instruction: 'Traduza para o inglês.',
        prompt: 'Ela tem 20 anos.',
        acceptedAnswers: [
          'She is 20 years old.',
          "She's 20 years old.",
          'She is twenty years old.',
          "She's twenty years old.",
          'She is 20.',
          "She's 20.",
          'She is twenty.',
          "She's twenty.",
        ],
        explanation: {
          pt: 'Para idade usamos o verbo to be: She is 20 years old (ou She\'s 20).',
          en: "Age uses the verb to be: She is 20 years old (or She's 20).",
        },
        skillTag: 'to_be',
      },
      {
        id: 'numbers-5',
        lessonId: 'numbers-age',
        type: 'multiple_choice',
        instruction: 'Escolha o número correto.',
        prompt: 'Qual número é "thirty"?',
        options: ['30', '13', '3', '33'],
        acceptedAnswers: ['30'],
        explanation: {
          pt: '"Thirty" termina em "-ty", então é uma dezena: 30. O 13 é "thirteen".',
          en: '"Thirty" ends in "-ty", so it is a ten: 30. 13 is "thirteen".',
        },
        skillTag: 'numbers',
      },
    ],
    practice: {
      opener: {
        en: "Let's talk about numbers! I'm {assistant}. How old are you?",
        pt: 'Vamos falar de números! Eu sou {assistant}. Quantos anos você tem?',
      },
      question: 'How old are you?',
    },
    takeaways: [
      '13–19 terminam em "-teen"; dezenas terminam em "-ty".',
      'Idade usa o verbo to be: I\'m 25 (years old).',
      'Pergunte com "How old are you?".',
    ],
  },
  {
    id: 'colors-objects',
    level: 'beginner',
    order: 5,
    title: 'Cores e objetos do dia a dia',
    topic: 'Colors & everyday objects',
    summary: 'Descreva objetos com cores e use "a" e "an".',
    estimatedMinutes: 8,
    skillTags: ['vocabulary', 'articles'],
    objectives: [
      'Nomear cores e objetos comuns',
      'Colocar o adjetivo antes do substantivo',
      'Escolher entre "a" e "an"',
    ],
    explanation: [
      {
        pt: 'Em inglês, o adjetivo (a cor) vem ANTES do substantivo: a red car (um carro vermelho), a blue bag (uma bolsa azul).',
        en: 'In English, the adjective comes BEFORE the noun: a red car, a blue bag.',
      },
      {
        pt: 'Adjetivos não têm plural nem gênero: two red cars, a red bag. Nunca "reds cars".',
        en: 'Adjectives have no plural form: two red cars, never "reds cars".',
      },
      {
        pt: 'Usamos "a" antes de som de consoante (a book, a phone) e "an" antes de som de vogal (an apple, an umbrella).',
        en: 'Use "a" before a consonant sound (a book) and "an" before a vowel sound (an apple, an umbrella).',
      },
    ],
    alternativeExplanations: [
      {
        pt: 'Pense na ordem "como é + o que é": red (como é) + car (o que é) = red car. É o inverso do português.',
        en: 'Think "what it looks like + what it is": red + car = red car.',
      },
      {
        pt: '"An" existe para facilitar a pronúncia: "a apple" fica difícil de falar, "an apple" flui melhor. O que importa é o SOM, não a letra.',
        en: '"An" makes pronunciation smoother: "an apple" flows better than "a apple". What matters is the SOUND, not the letter.',
      },
    ],
    table: {
      caption: 'Cores e objetos',
      headers: ['Cor', 'Português', 'Objeto', 'Português'],
      rows: [
        ['red', 'vermelho', 'book', 'livro'],
        ['blue', 'azul', 'phone', 'celular'],
        ['green', 'verde', 'bag', 'bolsa/mochila'],
        ['yellow', 'amarelo', 'key', 'chave'],
        ['black', 'preto', 'chair', 'cadeira'],
        ['white', 'branco', 'umbrella', 'guarda-chuva'],
      ],
    },
    examples: [
      { en: 'I have a red car.', pt: 'Eu tenho um carro vermelho.', highlight: 'red car' },
      { en: 'This is an orange umbrella.', pt: 'Este é um guarda-chuva laranja.', highlight: 'an orange' },
      { en: 'My keys are on the white chair.', pt: 'Minhas chaves estão na cadeira branca.', highlight: 'white chair' },
    ],
    extraExamples: [
      { en: 'She has a black phone.', pt: 'Ela tem um celular preto.', highlight: 'black phone' },
      { en: 'I need an eraser.', pt: 'Eu preciso de uma borracha.', highlight: 'an eraser' },
      { en: 'Two green books are on the table.', pt: 'Dois livros verdes estão na mesa.', highlight: 'green books' },
    ],
    vocabularyIds: ['red', 'blue', 'green', 'yellow', 'black', 'white', 'umbrella', 'phone', 'bag', 'key'],
    exercises: [
      {
        id: 'colors-1',
        lessonId: 'colors-objects',
        type: 'select_word',
        instruction: 'Selecione o artigo correto.',
        prompt: 'I have ___ umbrella.',
        options: ['an', 'a', 'some'],
        acceptedAnswers: ['an'],
        explanation: {
          pt: '"Umbrella" começa com som de vogal, então usamos "an": an umbrella.',
          en: '"Umbrella" starts with a vowel sound, so we use "an".',
        },
        skillTag: 'articles',
      },
      {
        id: 'colors-2',
        lessonId: 'colors-objects',
        type: 'multiple_choice',
        instruction: 'Escolha a tradução correta.',
        prompt: 'Como se diz "um carro vermelho"?',
        options: ['a red car', 'a car red', 'an red car', 'a reds car'],
        acceptedAnswers: ['a red car'],
        explanation: {
          pt: 'A cor (adjetivo) vem antes do objeto: a red car. E usamos "a" porque "red" começa com som de consoante.',
          en: 'The color comes before the noun: a red car. We use "a" because "red" starts with a consonant sound.',
        },
        skillTag: 'vocabulary',
      },
      {
        id: 'colors-3',
        lessonId: 'colors-objects',
        type: 'multiple_choice',
        instruction: 'Escolha o significado.',
        prompt: 'O que significa "yellow"?',
        options: ['amarelo', 'verde', 'vermelho', 'azul'],
        acceptedAnswers: ['amarelo'],
        explanation: {
          pt: '"Yellow" é amarelo — a cor do sol e da banana.',
          en: '"Yellow" is the color of the sun and bananas.',
        },
        skillTag: 'vocabulary',
      },
      {
        id: 'colors-4',
        lessonId: 'colors-objects',
        type: 'translate',
        instruction: 'Traduza para o inglês.',
        prompt: 'Meu celular é preto.',
        acceptedAnswers: [
          'My phone is black.',
          'My cell phone is black.',
          'My cellphone is black.',
          'My mobile phone is black.',
          'My mobile is black.',
        ],
        explanation: {
          pt: '"Celular" é "phone" (ou cell phone / mobile phone). A estrutura é: My phone + is + black.',
          en: '"Celular" is "phone" (or cell phone / mobile phone): My phone is black.',
        },
        skillTag: 'vocabulary',
      },
      {
        id: 'colors-5',
        lessonId: 'colors-objects',
        type: 'fill_blank',
        instruction: 'Complete com a cor em inglês (verdes).',
        prompt: 'She has two ___ bags.',
        acceptedAnswers: ['green'],
        explanation: {
          pt: 'Adjetivos não vão para o plural em inglês: two green bags (e não "greens").',
          en: 'Adjectives have no plural: two green bags (not "greens").',
        },
        skillTag: 'vocabulary',
      },
    ],
    practice: {
      opener: {
        en: "Let's describe things! I'm {assistant}. What color is your phone?",
        pt: 'Vamos descrever coisas! Eu sou {assistant}. Qual é a cor do seu celular?',
      },
      question: 'What color is your phone?',
    },
    takeaways: [
      'O adjetivo vem antes do substantivo: a blue bag.',
      'Adjetivos não têm plural: two blue bags.',
      '"An" antes de som de vogal: an umbrella.',
    ],
  },
];
